name: deploy to ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: deploy via ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            cd ~/Level-6Aws
            git fetch origin main
            git reset --hard origin/main
            sudo docker compose down
            sudo docker compose up -d --build
            sudo docker compose ps